name: Camera Obor FULL-HD PRO 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: sudo apt update && sudo apt install -y ffmpeg jq fonts-dejavu curl bc

      - name: Get Real Subs and Calculate Bar
        id: subs
        run: |
          RESPONSE=$(curl -s "https://www.googleapis.com/youtube/v3/channels?part=statistics&id=${{ secrets.CHANNEL_ID }}&key=${{ secrets.YOUTUBE_API_KEY }}")
          SUBS=$(echo $RESPONSE | jq -r '.items[0].statistics.subscriberCount')
          TARGET=1000
          PERCENT=$(echo "scale=2; $SUBS / $TARGET" | bc)
          if (( $(echo "$PERCENT > 1.0" | bc -l) )); then PERCENT=1.0; fi
          PERCENT_INT=$(echo "($SUBS * 100) / $TARGET" | bc)
          echo "subs_count=$SUBS" >> $GITHUB_OUTPUT
          echo "percent=$PERCENT" >> $GITHUB_OUTPUT
          echo "percent_int=$PERCENT_INT" >> $GITHUB_OUTPUT

      - name: Start Streaming (1080p + Pro Design)
        run: |
          ffmpeg -hide_banner -loglevel error \
          -rtsp_transport tcp \
          -analyzeduration 100M -probesize 100M \
          -re -i "${{ secrets.RTSP_URL }}" \
          -vf "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2, \
               drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='ROAD TO 1000 SUBS!':x=(w-text_w)/2:y=h-180:fontsize=35:fontcolor=white:shadowcolor=black:shadowx=3:shadowy=3, \
               drawbox=x=(w-806)/2:y=h-133:w=806:h=66:color=0xFF00FF@0.9:t=fill, \
               drawbox=x=(w-800)/2:y=h-130:w=800:h=60:color=black@0.9:t=fill, \
               drawbox=x=(w-800)/2:y=h-130:w=800*${{ steps.subs.outputs.percent }}:h=60:color=white@0.3:t=fill, \
               drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='${{ steps.subs.outputs.subs_count }} (${{ steps.subs.outputs.percent_int }}%)':x=(w-text_w)/2:y=h-115:fontsize=40:fontcolor=white" \
          -vcodec libx264 -preset veryfast -b:v 4500k -maxrate 4500k -bufsize 9000k -pix_fmt yuv420p \
          -acodec aac -ab 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_KEY }}"
